### ISSUE TITLE
Add SFTP upload action to repo

### ISSUE THREAD

**Issue by McMainsLiam** [McNerdCo/bga-1945#2]
@SeanMcTex 

I was thinking we could add a Github action to the repository that would automatically upload the repo to the SFTP server that BGA provides whenever we push to the main branch. I think these two things, with a custom npm script, would do the trick. There's probably a more efficient way, this is what I turned up on first pass though:

https://github.com/pirumpi/sftp-upload
https://github.com/actions/setup-node

What do you think? This way, we don't have to do it manually every time, and there won't be any confusion about "hey did you push to BGA... I was going to... did we overwrite each other..." and that sort of thing.

**Comment by SeanMcTex** [comment]
I like this idea! Two thoughts:

1. I'll definitely want to be uploading to the server frequently while I'm
working since I don't have a BGA server running here; I don't see anything
here that would prevent that, though it would mean the server may not be in
a known state when there's work in progress (and that if we're both doing
that, as seems likely, we might want to be careful about working on things
at the same time). And I'll probably want to reset the server back to a
known state when I'm done, or we add a scheduled job to reset the server to
what's in `main` each night or something.

2. There's a post on the BGA fora pointing to a similar tool:
https://forum.boardgamearena.com/viewtopic.php?f=12&t=13370&start=10#p59537
-- I've no preference for one set of code over another, but thought I'd
mention that others have trod here already.

**Comment by McMainsLiam** [comment]
Ahh, right. I forget there's not a great way to test locally before pushing up to their FTP server. Okay, well then yeah maybe we can do something similar but only have it trigger when we add a tag onto the PR, something like "deploy-to-bga". That way we can communicate beforehand about pushing the code up so we don't accidentally overwrite someone elses work in progress.

Thanks for sharing that link! That looks even better, doesn't require any npm setup :)

**Comment by SeanMcTex** [comment]
For my workflow, anyway, there's no big worry about overwriting work in
progress -- I'm using VSCode to edit files locally, and then syncing those
to the server to actually test them. While my server files *might* get
overwritten, it would only cause a few minutes of confusion, not any
lasting damage, since my files will still be on my box.
